DI-2029: DRAFT
jampp/migratron pull request #41
Opened 2021-11-05 16:03 UTC by Rcharriol

* [ ] Updated [CHANGELOG file](https://github.com/jampp/migratron/blob/master/CHANGELOG.rst)
* [ ] Created test for the code changes
* [ ] If required, [bumped the version](https://semver.org/)
* [ ] If required, updated the requirements.txt file

2021-11-08 17:29 UTC, viniolivieri requested changes

2021-11-08 17:29 UTC, viniolivieri commented on migratron/command/run_migration.py
> +                    "spark.sql.catalog.hive_prod.uri": "thrift://hive-metastore:9083"
```suggestion
                jars=["s3://artifacts.jampp.com/dw/code/iceberg-spark3-runtime-bc41476.jar"],
                spark_conf={
                    "spark.sql.catalog.iceberg": "org.apache.iceberg.spark.SparkCatalog",
                    "spark.sql.catalog.iceberg.type": "hive",
                    "spark.sql.catalog.iceberg.uri": "thrift://hive-metastore:9083"
```

2021-11-09 20:50 UTC, Rcharriol reviewed
![image](https://user-images.githubusercontent.com/37484826/141002406-eead09e8-94d9-4551-aa7b-91e47f22f834.png)
😜

2021-11-09 21:23 UTC, viniolivieri approved these changes

2021-11-10 14:29 UTC, merged